### PR TITLE
feat: implement novu topics

### PR DESCRIPTION
**Pull request by roman-utila**
Currently this sdk doesn't have a built-in support. In my company we selected novu as a solution, because of it's topics offering.

Adding implementation to the topics API, based on the documentation at https://docs.novu.co/api/

### CODE REVIEW

**Comment by samsoft00** [comment]
@roman-utila awesome, I'll review and feed you back.

**Comment by roman-utila** [comment]
@samsoft00 any news about this?

**Comment by unicodeveloper** [comment]
@samsoft00 Any updates? It will be nice to review and tag this as soon as possible because 0.12 just got tagged yesterday and will be released any time from now.

Let me know if you need any help 🙏🏿

**Comment by samsoft00** [comment]
@roman-utila apologies, I'm currently engaged but I'll be free this weekend to review it.
@unicodeveloper oh, that'll great. please go ahead. Appreciate it.

**Comment by unicodeveloper** [comment]
@samsoft00 please any update here?

**Comment by unicodeveloper** [comment]
Hi @samsoft00 Happy new week. Please can we get a review of this so that it can be merge in and published soonest? Thank you

**Review by unicodeveloper — APPROVED** [review]

**Comment by unicodeveloper** [comment]
@roman-utila Please can you update the readme (docs) for the features you added?

**Pull request merged**
