### PR TITLE
feat: bulk, broadcast and cancel Trigger Events

### LINKED ISSUE #10: [NV-GO-3] API 🚀: Bulk Trigger Event
🔖 Feature description

There should be a service that bulk triggers event

🎤 API Reference
https://docs.novu.co/api/bulk-trigger-event/

### PR DESCRIPTION
**Pull request by akhill10**
- Added Bulk, Broadcast, and Cancel Trigger Events
- Fixes #10

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@samsoft00 @prajjwaldimri Please can any of you review this?

**Comment by unicodeveloper** [comment]
Just pinging here again @samsoft00 @prajjwaldimri. Please take a look at this PR.

**Comment by samsoft00** [comment]
> Just pinging here again @samsoft00 @prajjwaldimri. Please take a look at this PR.

My apologies, my schedule has been quite full. However, I will have increased availability beginning next week. 👍

**Comment by unicodeveloper** [comment]
@akhill10 Please can you update the readme for this. Looking to merging and closing this out this week.

**Review by unicodeveloper — APPROVED** [review]

**Pull request merged**
